const $=s=>document.querySelector(s), content=$('#content'), title=$('#title');
setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString(),1000);
async function api(url,opt){const r=await fetch(url,opt); if(!r.ok)throw new Error(await r.text()); return r.json()}
function riskBadge(v){return `<span class="badge ${v}">${v}</span>`}
async function overview(){
 const [inv,trucks,dev,orders]=await Promise.all([api('/api/inventory/STORE-042'),api('/api/distribution/trucks'),api('/api/operations/STORE-042/devices'),api('/api/fulfillment/orders')]);
 const high=inv.filter(x=>x.risk==='HIGH').length, critical=dev.filter(x=>x.state==='CRITICAL').length, waiting=orders.filter(x=>x.status!=='READY').length;
 content.innerHTML=`<div class="grid"><div class="card span12 hero"><span class="label">LOGISTDRAGON / ECUADOR</span><h2>Operations Command Center</h2><p>Visibilidad unificada de inventario, distribución, activos de tienda y flujo de pedidos. El laboratorio traduce eventos físicos en decisiones operacionales observables.</p></div>
 ${[['DEMO','Entorno de referencia','good'],[high,'Riesgos de stock','bad'],[critical,'Activos críticos','bad'],[waiting,'Pedidos en proceso','warn']].map(x=>`<div class="card span3 kpi"><span class="label">${x[1]}</span><strong class="${x[2]}">${x[0]}</strong><small>Resumen técnico · últimos 20 pedidos</small></div>`).join('')}
 <div class="card span7"><span class="label">STORE-042 · INVENTORY RISK</span>${inventoryTable(inv)}</div>
 <div class="card span5"><span class="label">STORE-042 · EQUIPMENT</span>${devicesList(dev)}</div></div>`;
}
function inventoryTable(rows){return `<table><thead><tr><th>Producto</th><th>Stock</th><th>Demanda 4h</th><th>Riesgo</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r.item}</b></td><td>${r.stock} ${r.unit}</td><td>${r.forecast4h} ${r.unit}</td><td>${riskBadge(r.risk)}</td></tr>`).join('')}</tbody></table>`}
function devicesList(rows){return rows.map(d=>`<div class="device"><div><span class="dot ${d.state==='OK'?'good':d.state==='WARNING'?'warn':'bad'}"></span><b>${d.deviceId}</b><div class="muted">${d.online?'Online':'Offline'}</div></div><div><b>${d.temperatureC}°C</b><div>${riskBadge(d.state)}</div></div></div>`).join('')||'<p class="muted">Esperando telemetría MQTT…</p>'}
async function inventory(){const rows=await api('/api/inventory/STORE-042');content.innerHTML=`<div class="grid"><div class="card span12"><span class="label">SMART INVENTORY / STORE-042</span><h2>Disponibilidad vs demanda prevista</h2>${inventoryTable(rows)}</div>${rows.map(r=>`<div class="card span3 kpi"><span class="label">${r.item}</span><strong>${r.stock} <small>${r.unit}</small></strong><div class="meter"><span style="width:${Math.min(100,r.stock/r.forecast4h*100)}%"></span></div><p>${riskBadge(r.risk)}</p></div>`).join('')}</div>`}
async function distribution(){const rows=await api('/api/distribution/trucks');content.innerHTML=`<div class="grid">${rows.map(t=>`<div class="card span6"><span class="label">${t.truckId} · ${t.route}</span><h2>${t.status}</h2><p><b>${t.stopsDone}/${t.stopsTotal}</b> paradas · ETA <b>${t.etaMin} min</b></p><p>Cadena de frío: <b>${t.temperatureC}°C</b> ${riskBadge(t.coldChain==='OK'?'OK':'CRITICAL')}</p><p class="muted">GPS ${t.lat}, ${t.lon}</p><button class="action" onclick="advance('${t.truckId}')">Simular siguiente parada</button></div>`).join('')}</div>`}
async function advance(id){await api(`/api/distribution/trucks/${id}/advance`,{method:'POST'});distribution()}
async function operations(){const rows=await api('/api/operations/STORE-042/devices');content.innerHTML=`<div class="grid"><div class="card span12"><span class="label">SMART OPERATIONS · MQTT TELEMETRY</span><h2>STORE-042 equipment health</h2><p class="muted">Los dispositivos simulados publican telemetría al broker MQTT; Operations API la consume y la persiste en MongoDB.</p></div>${rows.map(d=>`<div class="card span4 kpi"><span class="label">${d.deviceId}</span><strong class="${d.state==='CRITICAL'?'bad':d.state==='WARNING'?'warn':'good'}">${d.temperatureC}°C</strong><p>${riskBadge(d.state)}</p><small>${new Date((d.ts||0)*1000).toLocaleTimeString()}</small></div>`).join('')}</div>`}
async function fulfillment(){const rows=await api('/api/fulfillment/orders');content.innerHTML=`<div class="grid"><div class="card span12"><span class="label">ORDER FULFILLMENT · EVENT DRIVEN</span><h2>Kitchen queue</h2><button class="action" onclick="newOrder()">+ Crear pedido demo</button><p class="muted">El API guarda el pedido y su outbox de forma atómica. El relay publica hechos y comandos en Redpanda. Un worker de cocina consume el evento y avanza WAITING → PREPARING → READY.</p></div><div class="card span12"><table><thead><tr><th>Pedido</th><th>Canal</th><th>Total</th><th>Estado</th><th>Última actualización</th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${o.orderId}</b></td><td>${o.channel}</td><td>${o.totalExact} DEMO</td><td>${riskBadge(o.status)}</td><td>${new Date(o.updatedAt*1000).toLocaleTimeString()}</td></tr>`).join('')}</tbody></table></div></div>`}
async function newOrder(){await api('/api/fulfillment/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storeId:'STORE-042',channel:'MOBILE',total:(18.5+Math.random()*20).toFixed(2)})});fulfillment();setTimeout(fulfillment,5000)}
async function platform(){let checks=await Promise.all(['inventory','logistics','operations','fulfillment'].map(async s=>{try{return [s,await api('/health/'+s)]}catch(e){return [s,{status:'DOWN'}]}}));content.innerHTML=`<div class="grid"><div class="card span12"><span class="label">PLATFORM ENGINEERING</span><h2>Runtime topology</h2><div class="flow"><span class="node">Browser</span><span class="arrow">→</span><span class="node">Nginx Edge</span><span class="arrow">→</span><span class="node">4 Domain APIs</span><span class="arrow">→</span><span class="node">PostgreSQL / MongoDB</span><span class="node">MQTT</span><span class="node">Redpanda</span></div></div>${checks.map(c=>`<div class="card span3 kpi"><span class="label">${c[0].toUpperCase()}</span><strong class="${c[1].status==='UP'?'good':'bad'}">${c[1].status}</strong><small>Health contract</small></div>`).join('')}<div class="card span12"><span class="label">OBSERVABILITY</span><h3>Prometheus → Grafana · cAdvisor → container metrics</h3><p class="muted">Abra los puertos 29090, 23000 y 28088 desde Codespaces para inspección operativa completa.</p></div></div>`}
let businessSocket, businessLastSeen=0, businessValue;
function escapeText(value){const e=document.createElement('span'); e.textContent=value??''; return e.innerHTML}
function renderBusiness(){
 if(document.querySelector('nav button.active')?.dataset.view!=='business')return;
 const expired=performance.now()-businessLastSeen>3000;
 const quality=expired?'STALE':businessValue?.quality.status||'STALE';
 const values=businessValue?.kpis||{};
 content.innerHTML=`<div class="grid"><div class="card span12"><span class="label">BUSINESS CONTRACT · 15 s · WINDOW 15 min</span><h2 data-testid="business-quality">${quality}</h2><p>${escapeText(expired?'La conexión o el reloj de snapshots no están disponibles.':businessValue?.quality.reason)}</p><a href="/grafana/d/logistpulse-business/logistpulse-business" target="_blank" rel="noopener">Abrir los paneles nativos de Grafana Live</a><p class="muted">El resumen de esta consola recibe snapshots por WebSocket. La prueba de latencia mide los paneles nativos de Grafana, de forma separada.</p></div>${Object.entries({'L-K1':'Promesas incumplidas (%)','L-K2':'Valor vencido (DEMO)','L-K3':'Deuda de preparación (pedido·segundos)'}).map(([key,label])=>{const item=values[key];const valid=quality==='FRESH';const display=!valid?'Sin datos confiables':item?.status==='NO_SAMPLE'?'Sin muestra':item?.value??'Pendiente';return `<div class="card span4 kpi"><span class="label">${key} · ${label}</span><strong class="${valid?(Number(item?.value)>0?'bad':'good'):'muted'}">${display}</strong><small>Muestra: ${item?.sample??'—'} · ${valid?item?.status:quality}</small></div>`}).join('')}<div class="card span12"><p>Último cálculo: ${escapeText(businessValue?.computedAt)} · revisión ${businessValue?.revision??'—'}</p><p>Agregados cubiertos: ${businessValue?.coverage.aggregateCount??'—'} · Cobertura ${quality==='FRESH'?'completa':'no confirmada'}</p><p>Correlación: ${escapeText(businessValue?.correlationId)} · versión ${businessValue?.sourceAggregateVersion??'—'}</p><button class="action" onclick="newOrder()">+ Crear pedido demo</button></div></div>`;
}
async function business(){
 renderBusiness();
 if(businessSocket && businessSocket.readyState<2)return;
 try{businessValue=await api('/api/business/snapshot');businessLastSeen=performance.now();renderBusiness()}catch(e){}
 businessSocket=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/api/business/ws`);
 businessSocket.onmessage=e=>{const next=JSON.parse(e.data);if(!businessValue||next.revision>businessValue.revision){businessValue=next;businessLastSeen=performance.now();renderBusiness()}};
 businessSocket.onclose=()=>{businessLastSeen=0;renderBusiness();if(document.querySelector('nav button.active')?.dataset.view==='business')setTimeout(business,500)};
}
setInterval(renderBusiness,500);
const views={overview,inventory,distribution,operations,fulfillment,platform,business};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');title.textContent=b.textContent.trim();views[b.dataset.view]()});
overview(); setInterval(()=>{if(document.querySelector('nav button.active')?.dataset.view==='overview')overview()},8000);
